version: "3.8"

x-postgres-common: &postgres-common
  image: postgres:alpine3.19
  user: postgres
  restart: always
  healthcheck:
    test: "pg_isready -U user --dbname=postgres"
    interval: 10s
    timeout: 5s
    retries: 5

services:
  auth-db:
    <<: *postgres-common
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
    networks:
      - ecommerce
      - auth
    volumes:
      - auth-db:/data/postgres

  auth:
    build: ./auth
    ports:
      - "5001:5001"
    environment:
      POSTGRES_HOST: auth-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
    networks:
      - ecommerce
      - auth
    depends_on:
      - auth-db

volumes:
  auth-db:

networks:
  auth:
  ecommerce:
